# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 890fe9e42d05ab5bc477aacfade6614703fa6b7c6fb0700657076f2d80dbbb54062f7376b39f3e971753ff2d64a3f2abba84e3c4359223a669a4bf07e5da1ca7

test:
  secret_key_base: 6e0292208334727eadd9eb8a1d6e838ce4a5104ab933b986a9d681aa727ac3dc6017b8c568272659dbe201a0682f6a3d57fd008c6835a9a00e33952e46fa5ac8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
